

export const SET_ACTIVE_USER_ID = "SET_ACTIVE_USER_ID";
export const SET_TYPING_VALUE = "SET_TYPING_VALUE";
export const SET_EDITING = "SET_EDITING";
export const SEND_MESSAGE = "SEND_MESSAGE";
export const SEARCH_CONTACTS = "SEARCH_CONTACTS";
export const DELETE_MESSAGE = "DELETE_MESSAGE";
export const EDIT_MESSAGE = "EDIT_MESSAGE";
